### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by TheFgut** [oleksandrblazhko/ai-214-gavrilyuk#22]
### 1
**оберіть за бажанням одну реальну потребу з таблиц**
>Я обрав потребу у бургерах з тунцем(Їжа)

### 2
**обґрунтуйте ваш вибір інформаційних умов, вказавши по одному реченню, чому для цих
умов забезпечено інформаційну задоволеність і вам не потрібно було нічого записувати у
відповідній комірці таблиці під час виконання лабораторної роботи (не плутати із задоволеністю
реальною потребою)**

Дані з таблиці про потребу:
Потреба  - бургер з тунцем(Їжа) 
доступність  - не завжди доступно 
зрозумілість  - зрозуміло |
цінність - цінно, бо це смачно 
актуальність  -актуально 

>Не завжди доступно – бо бюргери з тунцем це блюдо яке швидко псуеться і е любительським тому їх може бути важко знайти >у магазинах
>Зрозуміло – бо людям потрібно їсти, особливо те, що їм подобаеться, тому потреба у бюргерах зрозуміла
>Цінність – цінно, якщо людям подобаеться
>Актуально – через  невелику доступність  і через те що бюргери це їжа, а їжа потрібна у всі часи

### 1
**пригадайте мету вашого програмного продукту, створену у лабораторній роботі №1,
вказавши її у відповіді;**

>Мета:  Задовольнити потребу у бургерах з тунцем та тарілках з живописними малюнками до них, персональному бункері та >професійному спілкуванні.

### 2
**обґрунтуйте для трьох прецедентів той факт, що результати їх роботи дійсно наближають
користувача вашого програмного продукту до досягнення вказаної раніше мети.**

Feature1: Надавати усю потрібну інформацію для збудови бункера.
As a користувач.
In order to збудувати собі бункер щоб бути у безпеці.
I want to отримати інформацію як це робится і з якими проблемами я можу стовкнутися

>Цей прецедент наближає користувача до досягнення мети, бо знаючи як будувати бункер користувач зможе швидше його >збудувати.

Feature2: Інформація про виконання замовленнь у реальному часі
As a користувач
In order to планувати свій досуг.
I want to мати можливість знати стан виконання своїх замовленнь у сервісі.

>Цей прецедент наближає користувача до досягнення мети, бо знаючи на якому етапі виконання замовлення знаходиться >його замовлення, він зможе краще планувати свій досуг і витратити час поки замовлення виконується задовольняючи інші >потреби(наприклад у професійному спілкуванні, переписуючись на форумі)  бо буде знати коли воно виконається.

Feature3: Сповістити про успішність замовлення.
As a менеджер магазину.
In order to подзвонити/написати покупцю після того, як він оплатив замовлення.
I want to скористатися застосунком, який буде сповіщати мені, коли клієнт замовив товар.

>Цей прецедент наближає користувача до досягнення мети, бо якщо десь щось не спрацює або зламається у програмі під час >замовлення - покупець одразу дізнається про це, бо менеджер не подзвонив або подзвонив і сказав про це. Завдяки цьому >покупець не буде витрачати час на очікування товару, який не прийде, а працівники сервісу зможуть все полагодити і надати >необхідні послуги кліенту

**Comment by oleksandrblazhko** [comment]
2
